const canvas = document.getElementById('game-canvas');
const context = canvas.getContext('2d');
const keys = new Set();
const joystick = { x:0, y:0 };
const colors = { field:'#172728', wall:'#405553', wallLight:'#60756b', hero:'#54a89b', enemy:'#e66e45', boss:'#d84d5d', loot:'#e6bd54', shot:'#f7e9b4', text:'#d9e8d6' };
const rooms = ['THE SUNKEN VESTIBULE','MOSS LANTERN HALL','THE CLOCKWORK CRYPT','THE RED GALLERY','THE LAST THRESHOLD'];
const classes = {
  wanderer:{ name:'WANDERER', desc:'Balanced and brave', speed:180, damage:20, fireRate:.42, maxHealth:100, color:colors.hero },
  spark:{ name:'SPARK', desc:'Fast shots, fragile shell', speed:225, damage:13, fireRate:.21, maxHealth:75, color:'#8ecbd0' },
  bruiser:{ name:'BRUISER', desc:'Slow, heavy, hard to break', speed:135, damage:38, fireRate:.72, maxHealth:150, color:'#e59b5f' }
};
let state;
let controlsChosen = false;
let controlMode = null;
function resetRun() {
  state = { room:1, level:1, loot:0, health:100, score:0, combo:0, comboTimer:0, selectedClass:'wanderer', lastTime:0, fireTimer:0, dashTimer:0, shake:0, roomCleared:false, gateOpen:false, damageBoost:1, fireBoost:1, entities:[], shots:[], enemyShots:[], particles:[], decorations:[], player:{x:0,y:0,r:14}, keys: new Set() };
  resize(); generateRoom(); updateHud(); document.getElementById('end-modal').classList.add('hidden');
}
function resize() { const rect = canvas.getBoundingClientRect(); canvas.width = Math.max(320, Math.floor(rect.width * devicePixelRatio)); canvas.height = Math.max(300, Math.floor(rect.height * devicePixelRatio)); context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0); }
function size() { return { w:canvas.clientWidth, h:canvas.clientHeight }; }
function generateRoom() {
  const {w,h} = size(); state.player = {x:w/2,y:h/2,r:14}; state.entities=[]; state.shots=[]; state.enemyShots=[]; state.particles=[]; state.decorations=[]; state.roomCleared=false; state.gateOpen=false; state.combo=0; state.comboTimer=0;
  const count = 3 + Math.min(5,state.room + 1);
  for (let i=0;i<count;i++) state.entities.push(makeEnemy(false));
  if (state.room % 3 === 0) state.entities.push(makeEnemy(true));
  for (let i=0;i<2 + Math.floor(state.room/2);i++) state.entities.push({ type:'loot', x:55 + Math.random()*(w-110), y:55 + Math.random()*(h-110), r:9, spin:Math.random()*6 });
  for (let i=0;i<8;i++) state.decorations.push({ x:45+Math.random()*(w-90), y:45+Math.random()*(h-90), r:8+Math.random()*18, phase:Math.random()*Math.PI*2 });
  document.getElementById('room-name').textContent=rooms[(state.room-1)%rooms.length];
  addLog(`ROOM ${String(state.room).padStart(2,'0')}`, state.room % 3 === 0 ? 'A giant presence stirs.' : 'New walls, new trouble.');
  document.getElementById('wave-status').textContent = state.room % 3 === 0 ? 'BOSS ROOM' : 'CLEAR THE ROOM';
  if(state.room % 3 === 0) { state.shake=.35; burst(w/2,h/2,colors.boss,18); }
}
function makeEnemy(boss) { const {w,h}=size(); const edge=Math.floor(Math.random()*4); const x=edge===0?30:edge===1?w-30:50+Math.random()*(w-100); const y=edge===2?30:edge===3?h-30:50+Math.random()*(h-100); const regularHp=Math.ceil((35+state.room*5)*1.15); return {type:boss?'boss':'enemy',x,y,r:boss?34:11 + Math.random()*4,hp:boss?240:regularHp,maxHp:boss?240:regularHp,speed:boss?28:(38+Math.random()*20)*1.15,hit:0,fireTimer:1+Math.random()}; }
function selected() { return classes[state.selectedClass]; }
function update(dt) {
  if (!controlsChosen || state.health <= 0) return;
  const {w,h}=size(); const hero=state.player; const spec=selected(); let dx=0,dy=0;
  if (state.keys.has('w')||state.keys.has('arrowup')) dy--; if (state.keys.has('s')||state.keys.has('arrowdown')) dy++; if (state.keys.has('a')||state.keys.has('arrowleft')) dx--; if (state.keys.has('d')||state.keys.has('arrowright')) dx++;
  dx+=joystick.x; dy+=joystick.y;
  if (dx||dy) { const len=Math.hypot(dx,dy); hero.x += dx/len*spec.speed*dt; hero.y += dy/len*spec.speed*dt; }
  hero.x=Math.max(25,Math.min(w-25,hero.x)); hero.y=Math.max(25,Math.min(h-25,hero.y));
  state.fireTimer-=dt; state.dashTimer=Math.max(0,state.dashTimer-dt); state.shake=Math.max(0,state.shake-dt); state.comboTimer=Math.max(0,state.comboTimer-dt); if(state.comboTimer===0) state.combo=0;
  if (state.fireTimer<=0 && state.entities.some(e=>e.type==='enemy'||e.type==='boss')) { const target=state.entities.filter(e=>e.type==='enemy'||e.type==='boss').sort((a,b)=>dist(hero,a)-dist(hero,b))[0]; const angle=Math.atan2(target.y-hero.y,target.x-hero.x); state.shots.push({x:hero.x,y:hero.y,vx:Math.cos(angle)*390,vy:Math.sin(angle)*390,r:4,damage:spec.damage*state.damageBoost}); state.fireTimer=spec.fireRate*state.fireBoost; }
  for (const enemy of state.entities) { if (enemy.type==='loot') { enemy.spin+=dt*3; if(dist(hero,enemy)<hero.r+enemy.r+5){ state.loot++; state.score+=100; burst(enemy.x,enemy.y,colors.loot,8); enemy.dead=true; addLog('RELIC',`${state.loot} gathered. The circle changes.`); } continue; } const angle=Math.atan2(hero.y-enemy.y,hero.x-enemy.x); enemy.x+=Math.cos(angle)*enemy.speed*dt; enemy.y+=Math.sin(angle)*enemy.speed*dt; enemy.hit=Math.max(0,enemy.hit-dt); if(enemy.type==='boss'){enemy.fireTimer-=dt;if(enemy.fireTimer<=0){const aim=Math.atan2(hero.y-enemy.y,hero.x-enemy.x);state.enemyShots.push({x:enemy.x,y:enemy.y,vx:Math.cos(aim)*150,vy:Math.sin(aim)*150,r:7,life:4,telegraph:.45});enemy.fireTimer=1.2;burst(enemy.x,enemy.y,colors.boss,4);}} if(dist(hero,enemy)<hero.r+enemy.r && enemy.hit===0){state.health-=enemy.type==='boss'?16:8; state.combo=0; state.comboTimer=0; enemy.hit=.7; state.shake=.18; burst(hero.x,hero.y,colors.enemy,5); } }
  for(const shot of state.shots){shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;for(const enemy of state.entities){if(enemy.type!=='loot'&&!enemy.dead&&dist(shot,enemy)<shot.r+enemy.r){enemy.hp-=shot.damage;shot.dead=true;burst(shot.x,shot.y,colors.shot,3);if(enemy.hp<=0){enemy.dead=true;state.combo++;state.comboTimer=2.2;const reward=(enemy.type==='boss'?1000:150)*(1+Math.min(state.combo,10)*.1);state.score+=Math.round(reward);state.shake=enemy.type==='boss'?.35:.06;burst(enemy.x,enemy.y,enemy.type==='boss'?colors.boss:colors.enemy,enemy.type==='boss'?24:8);addLog(enemy.type==='boss'?'BOSS DOWN':'FOE DOWN',enemy.type==='boss'?'The giant circle breaks.':`${state.combo} in a row.`);}}}}
  for(const shot of state.enemyShots){shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;shot.life-=dt;shot.telegraph=Math.max(0,(shot.telegraph||0)-dt);if(dist(hero,shot)<hero.r+shot.r){shot.dead=true;state.health-=12;state.combo=0;state.comboTimer=0;state.shake=.18;burst(hero.x,hero.y,colors.boss,6);}}
  state.shots=state.shots.filter(s=>!s.dead&&s.x>-20&&s.x<w+20&&s.y>-20&&s.y<h+20); state.enemyShots=state.enemyShots.filter(s=>!s.dead&&s.life>0&&s.x>-20&&s.x<w+20&&s.y>-20&&s.y<h+20); state.entities=state.entities.filter(e=>!e.dead);
  if(!state.roomCleared&&!state.entities.some(e=>e.type==='enemy'||e.type==='boss')){state.roomCleared=true; state.score+=500; document.getElementById('wave-status').textContent='UPGRADE READY'; document.getElementById('upgrade-modal').classList.remove('hidden'); addLog('ROOM CLEAR','Choose an upgrade before the next room.');}
  if(state.gateOpen&&dist(hero,{x:w/2,y:25})<32){state.room++;state.level=Math.floor((state.room-1)/2)+1;generateRoom();}
  updateHud(); for(const particle of state.particles){particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.life-=dt;}state.particles=state.particles.filter(p=>p.life>0);
}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function burst(x,y,color,count){for(let i=0;i<count;i++){const angle=Math.random()*Math.PI*2,speed=30+Math.random()*80;state.particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:.35+Math.random()*.35,color});}}
function draw() { const {w,h}=size(); const now=Date.now(); context.clearRect(0,0,w,h); context.save(); if(state.shake) context.translate((Math.random()-.5)*5,(Math.random()-.5)*5); context.fillStyle=colors.field;context.fillRect(0,0,w,h); context.strokeStyle='rgba(180,220,190,.13)';context.lineWidth=2;context.strokeRect(24,24,w-48,h-48); for(const decoration of state.decorations){const glow=0.08+Math.sin(now/500+decoration.phase)*.03;context.fillStyle=`rgba(102,178,145,${glow})`;context.beginPath();context.arc(decoration.x,decoration.y,decoration.r,0,Math.PI*2);context.fill();context.strokeStyle='rgba(180,230,190,.12)';context.stroke();} if(state.gateOpen){context.strokeStyle=colors.loot;context.lineWidth=3;context.beginPath();context.arc(w/2,25,16+Math.sin(now/150)*4,0,Math.PI*2);context.stroke();context.fillStyle=colors.loot;context.font='9px DM Mono';context.fillText('EXIT',w/2-11,56);}
  for(const shot of state.shots){context.strokeStyle='rgba(247,233,180,.35)';context.lineWidth=3;context.beginPath();context.moveTo(shot.x-shot.vx*.035,shot.y-shot.vy*.035);context.lineTo(shot.x,shot.y);context.stroke();context.fillStyle=colors.shot;context.beginPath();context.arc(shot.x,shot.y,shot.r,0,Math.PI*2);context.fill();} for(const shot of state.enemyShots){context.strokeStyle='rgba(216,77,93,.28)';context.lineWidth=5;context.beginPath();context.moveTo(shot.x-shot.vx*.06,shot.y-shot.vy*.06);context.lineTo(shot.x,shot.y);context.stroke();if(shot.telegraph>0){context.strokeStyle=`rgba(255,190,159,${shot.telegraph*1.5})`;context.lineWidth=2;context.beginPath();context.arc(shot.x,shot.y,14+shot.telegraph*10,0,Math.PI*2);context.stroke();}context.fillStyle=colors.boss;context.strokeStyle='#ffbe9f';context.lineWidth=2;context.beginPath();context.arc(shot.x,shot.y,shot.r,0,Math.PI*2);context.fill();context.stroke();}
  for(const entity of state.entities){if(entity.type==='loot'){context.save();context.translate(entity.x,entity.y);context.rotate(entity.spin);context.fillStyle=colors.loot;context.beginPath();context.arc(0,0,entity.r,0,Math.PI*2);context.fill();context.strokeStyle='#fff0a4';context.lineWidth=2;context.stroke();context.restore();continue;}context.fillStyle=entity.type==='boss'?colors.boss:colors.enemy;context.globalAlpha=entity.hit?0.5:1;context.beginPath();context.arc(entity.x,entity.y,entity.r,0,Math.PI*2);context.fill();context.globalAlpha=1;if(entity.type==='boss'){context.strokeStyle='#ffbe9f';context.lineWidth=3;context.stroke();context.fillStyle=colors.text;context.font='9px DM Mono';context.textAlign='center';context.fillText('BOSS',entity.x,entity.y+3);context.fillStyle='#442d36';context.fillRect(entity.x-28,entity.y-45,56,4);context.fillStyle=colors.loot;context.fillRect(entity.x-28,entity.y-45,56*Math.max(0,entity.hp/entity.maxHp),4);}}
  const hero=state.player; const spec=selected();context.shadowColor=spec.color;context.shadowBlur=18;context.fillStyle=spec.color;context.beginPath();context.arc(hero.x,hero.y,hero.r,0,Math.PI*2);context.fill();context.shadowBlur=0;context.strokeStyle='#d6f2dc';context.lineWidth=3;context.stroke();context.fillStyle='rgba(255,255,255,.7)';context.beginPath();context.arc(hero.x-4,hero.y-4,3,0,Math.PI*2);context.fill(); if(state.combo>1&&state.comboTimer>0){context.fillStyle=colors.loot;context.font='600 16px Space Grotesk';context.textAlign='center';context.fillText(`x${state.combo} COMBO`,hero.x,hero.y-28);} for(const p of state.particles){context.globalAlpha=Math.max(0,p.life*2);context.fillStyle=p.color;context.beginPath();context.arc(p.x,p.y,2.5,0,Math.PI*2);context.fill();context.globalAlpha=1;} const vignette=context.createRadialGradient(w/2,h/2,Math.min(w,h)*.25,w/2,h/2,Math.max(w,h)*.72);vignette.addColorStop(0,'transparent');vignette.addColorStop(1,'rgba(3,12,13,.42)');context.fillStyle=vignette;context.fillRect(0,0,w,h); context.restore();}
function updateHud(){const spec=selected();document.getElementById('health-value').textContent=Math.max(0,Math.ceil(state.health));document.getElementById('health-meter').style.width=`${Math.max(0,state.health/spec.maxHealth*100)}%`;document.getElementById('level-value').textContent=String(state.level).padStart(2,'0');document.getElementById('loot-value').textContent=String(state.loot).padStart(2,'0');document.getElementById('depth-value').textContent=String(state.room).padStart(2,'0');document.getElementById('room-label').textContent=`ROOM ${String(state.room).padStart(2,'0')}`;document.getElementById('class-name').textContent=spec.name;document.getElementById('class-desc').textContent=spec.desc;document.getElementById('class-orb').style.color=spec.color;document.getElementById('class-orb').style.borderColor=spec.color; const spark=document.querySelector('[data-class="spark"]'),bruiser=document.querySelector('[data-class="bruiser"]');spark.classList.toggle('locked',state.loot<5);bruiser.classList.toggle('locked',state.loot<10);document.getElementById('unlock-note').textContent=state.loot<5?'Collect 5 relics to unlock SPARK.':state.loot<10?'Collect 10 relics to unlock BRUISER.':'All circle classes unlocked.';if(state.health<=0)endRun();}
function addLog(label,message){const log=document.getElementById('log-lines');const item=document.createElement('p');item.innerHTML=`<span>${label}</span> ${message}`;log.prepend(item);while(log.children.length>3)log.lastElementChild.remove();}
function endRun(){document.getElementById('run-state').textContent='RUN ENDED';document.getElementById('end-title').textContent='THE CIRCLE FADES';document.getElementById('end-copy').textContent=`You reached room ${state.room} with ${state.loot} relics.`;document.getElementById('end-modal').classList.remove('hidden');}
function loop(time){const dt=Math.min(.04,(time-state.lastTime)/1000||0);state.lastTime=time;update(dt);draw();requestAnimationFrame(loop);}
function dash(){if(!controlsChosen||state.health<=0||state.dashTimer>0)return;state.dashTimer=.8;const hero=state.player;let dx=(state.keys.has('d')?1:state.keys.has('a')?-1:0)+joystick.x,dy=(state.keys.has('s')?1:state.keys.has('w')?-1:0)+joystick.y;const length=Math.hypot(dx,dy);if(length){hero.x=Math.max(25,Math.min(size().w-25,hero.x+dx/length*70));hero.y=Math.max(25,Math.min(size().h-25,hero.y+dy/length*70));}burst(hero.x,hero.y,colors.hero,10);}
window.addEventListener('keydown',event=>{if(!controlsChosen)return;const key=event.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){event.preventDefault();state.keys.add(key);}if(key==='r')resetRun();if(key===' '){event.preventDefault();dash();}});window.addEventListener('keyup',event=>state.keys.delete(event.key.toLowerCase()));window.addEventListener('resize',resize);
document.querySelectorAll('[data-control-mode]').forEach(button=>button.addEventListener('click',()=>{controlMode=button.dataset.controlMode;controlsChosen=true;document.getElementById('controls-modal').classList.add('hidden');document.getElementById('mobile-controls').classList.toggle('active',controlMode==='mobile');document.getElementById('canvas-hint').textContent=controlMode==='mobile'?'JOYSTICK TO MOVE · DASH BUTTON TO DODGE':'WASD / ARROWS TO MOVE';document.querySelector('.arena-foot span:first-child').innerHTML=controlMode==='mobile'?'<i class="key">JOYSTICK</i> MOVE':'<i class="key">WASD</i> MOVE';}));
const moveStick=document.getElementById('move-stick'), moveKnob=moveStick.querySelector('.virtual-stick-knob');let stickPointer=null;
function updateJoystick(event){const bounds=moveStick.getBoundingClientRect(),limit=bounds.width*.34,dx=event.clientX-(bounds.left+bounds.width/2),dy=event.clientY-(bounds.top+bounds.height/2),length=Math.hypot(dx,dy),scale=length>limit?limit/length:1,x=dx*scale,y=dy*scale;moveKnob.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;joystick.x=x/limit;joystick.y=y/limit;}
function releaseJoystick(){stickPointer=null;joystick.x=0;joystick.y=0;moveKnob.style.transform='translate(-50%,-50%)';}
moveStick.addEventListener('pointerdown',event=>{event.preventDefault();stickPointer=event.pointerId;moveStick.setPointerCapture(stickPointer);updateJoystick(event);});moveStick.addEventListener('pointermove',event=>{if(event.pointerId===stickPointer)updateJoystick(event);});moveStick.addEventListener('pointerup',releaseJoystick);moveStick.addEventListener('pointercancel',releaseJoystick);document.getElementById('mobile-dash').addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();dash();});
document.querySelectorAll('.class-option').forEach(button=>button.addEventListener('click',()=>{const type=button.dataset.class;if(button.classList.contains('locked'))return;state.selectedClass=type;document.querySelectorAll('.class-option').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');state.health=Math.min(state.health,selected().maxHealth);updateHud();addLog('CLASS',`${selected().name} takes the lead.`);}));document.querySelectorAll('.upgrade-choice').forEach(button=>button.addEventListener('click',()=>{const upgrade=button.dataset.upgrade;if(upgrade==='vitality')state.health=Math.min(selected().maxHealth,state.health+25);if(upgrade==='power')state.damageBoost*=1.2;if(upgrade==='haste')state.fireBoost*=.85;state.gateOpen=true;document.getElementById('upgrade-modal').classList.add('hidden');document.getElementById('wave-status').textContent='GATE OPEN';addLog('UPGRADE',button.querySelector('strong').textContent+' acquired.');updateHud();}));document.getElementById('restart-button').addEventListener('click',resetRun);resetRun();requestAnimationFrame(loop);
