const canvas = document.getElementById('game-canvas');
const context = canvas.getContext('2d');
const waveButton = document.getElementById('wave-button');
const restartButton = document.getElementById('restart-button');
const hint = document.getElementById('canvas-hint');
const healthValue = document.getElementById('health-value');
const healthMeter = document.getElementById('health-meter');
const waveValue = document.getElementById('wave-value');
const waveLabel = document.getElementById('wave-label');
const waveStatus = document.getElementById('wave-status');
const scoreValue = document.getElementById('score-value');
const moneyValue = document.getElementById('money-value');
const deployStatus = document.getElementById('deploy-status');
const towerCostLabel = document.getElementById('tower-cost-label');
const towerCostValue = document.getElementById('tower-cost-value');
const towerOptions = document.querySelectorAll('.tower-option');
const logLines = document.getElementById('log-lines');

let towers = [], enemies = [], projectiles = [], walls = [], particles = [], wave = 1, score = 0, health = 100, money = 100;
let waveActive = false, spawnLeft = 0, spawnTimer = 0, bossPending = false, lastTime = 0, elapsed = 0, saveTimer = 0, selectedTower = 'sentry';
const towerTypes = {
  sentry: { label: 'SENTRY', key: '1', cost: 50, range: 145, fireRate: .62, damage: 1, color: '#1aa3a2', aura: '#65e6cf' },
  freezer: { label: 'FREEZER', key: '2', cost: 75, range: 125, fireRate: .9, damage: 1, color: '#70c8e8', aura: '#b7f3ff' },
  supporter: { label: 'SUPPORTER', key: '3', cost: 100, range: 95, fireRate: 1, damage: 0, boost: .15, color: '#d6e65e', aura: '#f4ff9b' },
  nuker: { label: 'NUKER', key: '4', cost: 150, range: 180, fireRate: 2.4, damage: 3, color: '#f36f3b', aura: '#ffbd65' },
  sniper: { label: 'SNIPER', key: '5', cost: 125, range: 240, fireRate: 1.8, damage: 5, color: '#c18cff', aura: '#e2c5ff' },
  rapid: { label: 'RAPID', key: '6', cost: 110, range: 120, fireRate: .22, damage: 1, color: '#ffcf5c', aura: '#fff2a6' },
  blocker: { label: 'BLOCKER', key: '7', cost: 200, range: 140, fireRate: 1.5, abilityCooldown: 7.5, damage: 0, color: '#f58eb7', aura: '#ffd0e4' },
  artillery: { label: 'ARTILLERY', key: '8', cost: 225, range: 260, fireRate: 3.2, damage: 4, area: 55, color: '#9aa3a8', aura: '#a56cff' }
};
const towerKeys = ['sentry', 'freezer', 'supporter', 'nuker', 'sniper', 'rapid', 'blocker', 'artillery'];

window.addEventListener('error', event => {
  const message = event.error?.message || event.message || 'Unknown runtime error';
  if (logLines) { const line = document.createElement('p'); line.innerHTML = `<span>ERROR</span> ${message}`; logLines.prepend(line); }
});

function resize() { const bounds = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; canvas.width = bounds.width * ratio; canvas.height = bounds.height * ratio; context.setTransform(ratio, 0, 0, ratio, 0, 0); }
function emitAttackParticles(tower, type, target) { const angle = Math.atan2(target.y - tower.y, target.x - tower.x); for (let index = 0; index < 7; index++) { const spread = (Math.random() - .5) * .8; particles.push({ x: tower.x, y: tower.y, vx: Math.cos(angle + spread) * (35 + Math.random() * 45), vy: Math.sin(angle + spread) * (35 + Math.random() * 45), life: .35 + Math.random() * .25, maxLife: .6, color: type.aura }); } }
function getPath() { const width = canvas.clientWidth, height = canvas.clientHeight; return [{ x: -18, y: height * .12 }, { x: width * .12, y: height * .12 }, { x: width * .12, y: height * .84 }, { x: width * .36, y: height * .84 }, { x: width * .36, y: height * .27 }, { x: width * .64, y: height * .27 }, { x: width * .64, y: height * .78 }, { x: width * .88, y: height * .78 }, { x: width * .88, y: height * .48 }, { x: width / 2, y: height / 2 }]; }
function addLog(message) { const line = document.createElement('p'); line.innerHTML = `<span>${String(Math.floor(elapsed)).padStart(2, '0')}:${String(Math.floor((elapsed % 1) * 60)).padStart(2, '0')}</span> ${message}`; logLines.prepend(line); while (logLines.children.length > 3) logLines.lastChild.remove(); }
function saveGame() { try { localStorage.setItem('orbitWardensSave', JSON.stringify({ towers, enemies, walls, wave, score, health, money, waveActive, spawnLeft, spawnTimer, bossPending, elapsed, selectedTower })); } catch (error) { addLog('Autosave unavailable in this browser.'); } }
function loadGame() { try { const saved = JSON.parse(localStorage.getItem('orbitWardensSave')); if (!saved) return; towers = saved.towers || []; enemies = saved.enemies || []; walls = saved.walls || []; projectiles = []; particles = []; wave = saved.wave || 1; score = saved.score || 0; health = saved.health ?? 100; money = saved.money ?? 100; waveActive = saved.waveActive || false; spawnLeft = saved.spawnLeft || 0; spawnTimer = saved.spawnTimer || 0; bossPending = saved.bossPending || false; elapsed = saved.elapsed || 0; selectedTower = towerTypes[saved.selectedTower] ? saved.selectedTower : 'sentry'; addLog('Autosave restored.'); } catch (error) { localStorage.removeItem('orbitWardensSave'); } }
function startWave() { if (waveActive || health <= 0) return; waveActive = true; spawnLeft = wave >= 10 ? 14 + wave * 3 : 4 + wave * 2; bossPending = wave >= 10 && wave % 5 === 0; spawnTimer = 0; waveStatus.textContent = bossPending ? 'BOSS INCOMING' : 'INCOMING'; addLog(`${bossPending ? 'Boss wave' : 'Wave'} ${String(wave).padStart(2, '0')} breached perimeter.`); }
function restart() { towers = []; enemies = []; projectiles = []; walls = []; particles = []; wave = 1; score = 0; health = 100; money = 100; waveActive = false; bossPending = false; updateUI(); addLog('Sector reset. Awaiting deployment.'); }
function updateUI() { const type = towerTypes[selectedTower]; healthValue.textContent = health; healthMeter.style.width = `${health}%`; moneyValue.textContent = String(money).padStart(3, '0'); towerCostLabel.textContent = `${type.label} COST`; towerCostValue.textContent = String(type.cost).padStart(3, '0'); waveValue.textContent = String(wave).padStart(2, '0'); waveLabel.textContent = `WAVE ${String(wave).padStart(2, '0')}`; scoreValue.textContent = String(score).padStart(4, '0'); waveStatus.textContent = health <= 0 ? 'CORE LOST' : bossPending ? 'BOSS INCOMING' : waveActive ? 'INCOMING' : 'STANDBY'; deployStatus.textContent = money < type.cost ? `${type.label} LOCKED · NEED CREDITS` : `${type.label} READY · ${type.cost} CREDITS`; hint.textContent = `${type.key} ${type.label} - CLICK THE FIELD TO DEPLOY`; towerOptions.forEach(option => option.classList.toggle('selected', option.dataset.tower === selectedTower)); }
function selectTower(type) { selectedTower = type; addLog(`${towerTypes[type].label} selected.`); updateUI(); }
function placeTower(event) { const type = towerTypes[selectedTower]; if (health <= 0) return; if (money < type.cost) { addLog(`Insufficient credits for ${type.label.toLowerCase()}.`); return; } const rect = canvas.getBoundingClientRect(); const x = event.clientX - rect.left, y = event.clientY - rect.top; if (Math.hypot(x - canvas.clientWidth / 2, y - canvas.clientHeight / 2) < 43 || towers.some(tower => Math.hypot(x - tower.x, y - tower.y) < 28)) return; towers.push({ x, y, type: selectedTower, cooldown: 0, pulse: 0 }); money -= type.cost; hint.style.display = 'none'; addLog(`${type.label} deployed. -${type.cost} credits.`); }
function spawnEnemy(isBoss = false) { const path = getPath(); const lateWave = wave >= 10; const normalHp = lateWave ? 4 + Math.floor((wave - 10) / 2) : 1 + Math.floor(wave / 3); const hp = isBoss ? normalHp * 25 : normalHp; enemies.push({ x: path[0].x, y: path[0].y, pathIndex: 1, speed: isBoss ? (lateWave ? 24 + (wave - 10) * 1.5 : 18 + wave * 1.5) : (lateWave ? 30 + (wave - 10) * 2 : 18 + wave * 1.5), hp, maxHp: hp, radius: isBoss ? 18 : 8 + Math.random() * 3, slow: 0, coreDamage: isBoss ? 25 : lateWave ? 12 : 8, boss: isBoss }); }
function update(delta) { elapsed += delta; if (waveActive && spawnLeft > 0) { spawnTimer -= delta; if (spawnTimer <= 0) { spawnEnemy(); spawnLeft--; spawnTimer = .45; } } if (waveActive && spawnLeft === 0 && bossPending && enemies.length === 0) { spawnEnemy(true); bossPending = false; addLog('BOSS ENTERED THE SECTOR.'); } if (waveActive && spawnLeft === 0 && !bossPending && enemies.length === 0) { waveActive = false; wave++; addLog('Perimeter clear. Nice work.'); }
  saveTimer += delta; if (saveTimer >= 2) { saveTimer = 0; saveGame(); }
  const center = { x: canvas.clientWidth / 2, y: canvas.clientHeight / 2 };
  const path = getPath();
  enemies.forEach(enemy => { const target = path[enemy.pathIndex]; const distance = Math.hypot(target.x - enemy.x, target.y - enemy.y); enemy.slow = Math.max(0, enemy.slow - delta); const speed = enemy.speed * (enemy.slow > 0 ? .35 : 1); const nextX = enemy.x + (target.x - enemy.x) / distance * speed * delta; const nextY = enemy.y + (target.y - enemy.y) / distance * speed * delta; const blocked = walls.some(wall => Math.hypot(wall.x - nextX, wall.y - nextY) < 19); if (distance < 4) { enemy.pathIndex++; if (enemy.pathIndex >= path.length) { enemy.dead = true; health = Math.max(0, health - enemy.coreDamage); } } else if (!blocked) { enemy.x = nextX; enemy.y = nextY; } });
  particles.forEach(particle => { particle.x += particle.vx * delta; particle.y += particle.vy * delta; particle.life -= delta; });
  particles = particles.filter(particle => particle.life > 0);
  walls.forEach(wall => { wall.life -= delta; });
  walls = walls.filter(wall => wall.life > 0);
  towers.forEach(tower => { const type = towerTypes[tower.type]; tower.cooldown -= delta; tower.pulse += delta; if (tower.cooldown <= 0) { const target = enemies.find(enemy => !enemy.dead && Math.hypot(enemy.x - tower.x, enemy.y - tower.y) < type.range); if (target && tower.type === 'blocker') { const destination = path[target.pathIndex]; const distance = Math.hypot(destination.x - target.x, destination.y - target.y); if (distance > 0) { emitAttackParticles(tower, type, target); walls.push({ x: target.x + (destination.x - target.x) / distance * 24, y: target.y + (destination.y - target.y) / distance * 24, life: 3, angle: Math.atan2(destination.y - target.y, destination.x - target.x) }); } tower.cooldown = type.abilityCooldown; } else if (target && type.damage > 0) { emitAttackParticles(tower, type, target); projectiles.push({ x: tower.x, y: tower.y, target, speed: 260, type: tower.type, damage: type.damage }); tower.cooldown = type.fireRate; } } });
  towers.forEach(other => { const nearbySupporters = towers.filter(tower => tower.type === 'supporter' && tower !== other && Math.hypot(other.x - tower.x, other.y - tower.y) < towerTypes.supporter.range); other.cooldown -= delta * Math.min(.75, nearbySupporters.length * towerTypes.supporter.boost); nearbySupporters.forEach(supporter => { supporter.supportParticleTimer = (supporter.supportParticleTimer || 0) - delta; if (supporter.supportParticleTimer <= 0) { emitAttackParticles(supporter, towerTypes.supporter, other); supporter.supportParticleTimer = .35; } }); });
  projectiles.forEach(projectile => { if (!projectile.target || projectile.target.dead) { projectile.dead = true; return; } const distance = Math.hypot(projectile.target.x - projectile.x, projectile.target.y - projectile.y); if (distance < 7) { if (projectile.type === 'freezer') projectile.target.slow = 1.8; const area = towerTypes[projectile.type].area || 0; if (area) enemies.filter(enemy => Math.hypot(enemy.x - projectile.target.x, enemy.y - projectile.target.y) < area).forEach(enemy => { enemy.hp -= projectile.damage; }); else projectile.target.hp -= projectile.damage; projectile.dead = true; if (projectile.target.hp <= 0) { projectile.target.dead = true; score += projectile.target.boss ? 625 : 25; money += projectile.target.boss ? 625 : 25; } } else { projectile.x += (projectile.target.x - projectile.x) / distance * projectile.speed * delta; projectile.y += (projectile.target.y - projectile.y) / distance * projectile.speed * delta; } });
  enemies = enemies.filter(enemy => !enemy.dead); projectiles = projectiles.filter(projectile => !projectile.dead); updateUI(); }
function draw() { const width = canvas.clientWidth, height = canvas.clientHeight; context.clearRect(0, 0, width, height); const cx = width / 2, cy = height / 2; const path = getPath(); context.strokeStyle = '#395457'; context.lineWidth = 1; [42, 100, 166].forEach(radius => { context.beginPath(); context.arc(cx, cy, radius, 0, Math.PI * 2); context.stroke(); }); context.save(); context.shadowBlur = 0; context.strokeStyle = '#385256'; context.lineWidth = 22; context.lineCap = 'round'; context.lineJoin = 'round'; context.beginPath(); context.moveTo(path[0].x, path[0].y); path.slice(1).forEach(point => context.lineTo(point.x, point.y)); context.stroke(); context.strokeStyle = '#293f42'; context.lineWidth = 16; context.stroke(); context.restore(); context.fillStyle = '#d6e65e'; context.shadowColor = '#d6e65e'; context.shadowBlur = 15; context.beginPath(); context.arc(cx, cy, 17, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; context.fillStyle = '#1e3134'; context.beginPath(); context.arc(cx, cy, 6, 0, Math.PI * 2); context.fill();
  walls.forEach(wall => { context.save(); context.translate(wall.x, wall.y); context.rotate(wall.angle); context.fillStyle = '#f58eb7'; context.shadowColor = '#f58eb7'; context.shadowBlur = 10; context.fillRect(-5, -24, 10, 48); context.restore(); }); towers.forEach(tower => { const type = towerTypes[tower.type]; if (type.aura) { context.strokeStyle = type.aura; context.globalAlpha = .55 + Math.sin(tower.pulse * 4) * .15; context.lineWidth = 3; context.beginPath(); context.arc(tower.x, tower.y, 20 + Math.sin(tower.pulse * 3) * 2, 0, Math.PI * 2); context.stroke(); context.globalAlpha = 1; } context.fillStyle = type.color; context.shadowColor = type.aura || type.color; context.shadowBlur = 13; context.beginPath(); context.arc(tower.x, tower.y, 12 + Math.sin(tower.pulse * 5) * 1.5, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; context.fillStyle = '#d5f0d7'; context.beginPath(); context.arc(tower.x, tower.y, 5, 0, Math.PI * 2); context.fill(); });
  enemies.forEach(enemy => { context.fillStyle = enemy.boss ? '#f05a32' : '#f36f3b'; context.shadowColor = enemy.boss ? '#ffcf5c' : '#ff9a5d'; context.shadowBlur = enemy.boss ? 18 : 11; context.beginPath(); context.arc(enemy.x, enemy.y, enemy.radius, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; context.fillStyle = '#ffd16f'; context.beginPath(); context.arc(enemy.x, enemy.y, enemy.boss ? 7 : 3, 0, Math.PI * 2); context.fill(); context.fillStyle = '#557274'; context.fillRect(enemy.x - (enemy.boss ? 20 : 9), enemy.y - enemy.radius - 7, enemy.boss ? 40 : 18, 3); context.fillStyle = enemy.boss ? '#ffd16f' : '#f36f3b'; context.fillRect(enemy.x - (enemy.boss ? 20 : 9), enemy.y - enemy.radius - 7, (enemy.boss ? 40 : 18) * (enemy.hp / enemy.maxHp), 3); });
  particles.forEach(particle => { context.globalAlpha = Math.max(0, particle.life / particle.maxLife); context.fillStyle = particle.color; context.shadowColor = particle.color; context.shadowBlur = 8; context.beginPath(); context.arc(particle.x, particle.y, 2.5, 0, Math.PI * 2); context.fill(); }); context.globalAlpha = 1; projectiles.forEach(projectile => { context.fillStyle = '#d6e65e'; context.beginPath(); context.arc(projectile.x, projectile.y, 3, 0, Math.PI * 2); context.fill(); }); }
function loop(timestamp) { const delta = Math.min((timestamp - lastTime) / 1000 || 0, .05); lastTime = timestamp; update(delta); draw(); requestAnimationFrame(loop); }
canvas.addEventListener('click', placeTower); towerOptions.forEach(option => option.addEventListener('click', () => selectTower(option.dataset.tower))); waveButton.addEventListener('click', startWave); restartButton.addEventListener('click', restart); window.addEventListener('resize', resize); window.addEventListener('beforeunload', saveGame); window.addEventListener('keydown', event => { if (event.code === 'Space') { event.preventDefault(); startWave(); } if (event.key.toLowerCase() === 'r') restart(); const towerIndex = Number(event.key) - 1; if (towerIndex >= 0 && towerIndex < towerKeys.length) selectTower(towerKeys[towerIndex]); }); loadGame(); resize(); updateUI(); requestAnimationFrame(loop);
